### ISSUE TITLE
Packages target netcoreapp instead of netstandard

### ISSUE THREAD

**Issue by vaindil** [claytondus/Claytondus.AmazonMWS#2]
Hello! Some of the packages are targeting `netcoreapp1.1` instead of `netstandardX`. Not sure if it's intentional, reporting it just in case.

 * FbaInbound
 * FbaOutbound
 * Orders
 * Products
 * Runtime

**Comment by claytondus** [comment]
This is intentional, I am going to release a new version with targeting netstandard2.0 and netcoreapp1.1 as soon as I can get to it.

**Comment by claytondus** [comment]
Packages targeting netstandard2.0, netcoreapp1.1, and net46 have been published to NuGet.
