### ISSUE TITLE
Reports package

### ISSUE THREAD

**Issue by ragnarek81997** [claytondus/Claytondus.AmazonMWS#6]
Hi @claytondus, I found that you haven't published Claytondus.AmazonMWS.Reports package, so I'm just wondering if you're doing it?

**Comment by claytondus** [comment]
The functions of the Reports module can be found in the Feeds module.  I need to remove the redundant code from the repo (Claytondus.AmazonMWS.Reports shouldn't exist).

**Comment by ragnarek81997** [comment]
thanks, don’t know that
